apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: deploy-onpkapp
      taskRef:
        name: helm-upgrade-from-source
      params:
        - name: release
          value: "onpkapp"
        - name: chart
          value: "./Helm/onpkapp"
        - name: namespace
          value: "default"
        - name: values
          value: |
            frontend:
              replicas: 2
              image: docker.io/tomanAdrian/appfrontend:1.0.0
              service:
                type: ClusterIP
                port: 8080
            backend:
              replicas: 1
              image: docker.io/tomanAdrian/appbackend:1.0.0
              service:
                type: ClusterIP
                port: 9080
      workspaces:
        - name: shared-workspace
          workspace: shared-workspace
