
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  tasks:
    - name: clone-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: "https://github.com/tomanAdrian/ONPK-2024-Toman.git"
        - name: revision
          value: "main"
      workspaces:
        - name: output
          workspace: shared-workspace

    - name: build-frontend-image
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: "docker.io/tomanAdrian/appfrontend:1.0.0"
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: push-frontend-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: "docker.io/tomanAdrian/appfrontend:1.0.0"
      runAfter:
        - build-frontend-image
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: build-backend-image
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: "docker.io/tomanAdrian/appbackend:1.0.0"
      runAfter:
        - clone-repo
      workspaces:
        - name: source
          workspace: shared-workspace

    - name: push-backend-image
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: "docker.io/tomanAdrian/appbackend:1.0.0"
      runAfter:
        - build-backend-image
      workspaces:
        - name: source
          workspace: shared-workspace

workspaces:
  - name: shared-workspace
