apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-onpkapp
  namespace: onpkapp
  labels:
    app: be-onpkapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-onpkapp
  template:
    metadata:
      labels:
        app: be-onpkapp
    spec:
      containers:
        - name: be-onpkapp-container
          image: peter510/appbackend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9080
          env:
          - name: MONGO_CONN_STR
            value: mongodb://onpkapp-mongodb:27017/platformsdb
          - name: MONGO_AUTH_SOURCE
            value: platformsdb
          - name: MONGO_USERNAME
            value: admin
          - name: MONGO_PASSWORD
            value: password
          - name: LISTEN_PORT
            value: "9080"