apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onpkapp-backend-ingress
  namespace: onpkapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: "nginx"
  rules:
  - host: onpkapp.mydomain.local
    http:
      paths:
      - path: /platforms
        pathType: Prefix
        backend:
          service:
            name: onpkapp-backend
            port:
              number: 9080
