apiVersion: v1
kind: Service
metadata:
  name: onpkapp-backend
  namespace: onpkapp
  labels:
    app: be-onpkapp
spec:
  type: ClusterIP
  ports:
    - port: 9080
      targetPort: 9080
      protocol: TCP
  selector:
    app: be-onpkapp